// src/data/featuresData.js
import {
  FaCalendarDay,
  FaUserPlus,
  FaMoneyBillWave,
  FaBed,
  FaTools,
  FaUtensils,
  FaBullhorn,
  FaChartLine,
  FaMobileAlt,
  FaHeadset,
  FaShieldAlt,
  FaWifi,
  FaLock,
  FaBolt,
  FaUsers,
  FaFileContract,
} from "react-icons/fa";

export const featuresData = [
  {
    id: "day-booking",
    title: "Smart Day-wise Room Booking",
    tag: "Booking",
    description: "Booking system for short stays with instant confirmation.",
    longDescription: "Revolutionize your hostel booking with our intelligent day-wise booking system that operates exactly like OYO. Allow guests, students, and professionals to book rooms for any duration—daily, weekly, or monthly—without long-term commitments. Our system automatically calculates pricing based on dynamic rates, checks real-time availability, and generates instant invoices. Perfect for hostels, PGs, and service apartments looking to maximize occupancy through flexible stays.",
    icon: FaCalendarDay,
    color: "from-blue-500 to-indigo-600",
    points: [
      "Daily/weekly/monthly flexible stays",
      "Real-time availability calendar",
      "Instant confirmation & automated invoices",
      "Dynamic pricing based on demand",
      "No-show protection & cancellation policies",
    ],
    benefits: [
      "Increase occupancy by 40% with short-term bookings",
      "Eliminate manual booking conflicts entirely",
      "OYO-like seamless booking experience",
      "Automated pricing reduces human errors",
      "24/7 booking without staff intervention",
    ],
    workflow: [
      "Guest selects dates on live calendar",
      "System checks real-time availability",
      "Dynamic pricing calculation",
      "Secure payment processing",
      "Instant confirmation & digital key",
      "Automated check-in/checkout reminders",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
    ],
    stats: [
      { label: "Booking Speed", value: "90% faster" },
      { label: "Occupancy Boost", value: "+40%" },
      { label: "Error Reduction", value: "95%" },
    ],
  },
  {
    id: "tenant-onboarding",
    title: "Digital Tenant Onboarding & KYC",
    tag: "Onboarding",
    description: "Paperless onboarding with ID verification and smart allocation.",
    longDescription: "Transform your tenant onboarding from days to minutes with our fully digital KYC system. Capture tenant details, verify identities, conduct background checks, and allocate rooms—all through a single platform. The system automatically generates digital agreements, collects e-signatures, and prepares police verification documents. Smart allocation algorithms consider gender, preferences, and special requirements to ensure perfect placements.",
    icon: FaUserPlus,
    color: "from-emerald-500 to-teal-600",
    points: [
      "Digital KYC with document upload",
      "AI-powered ID verification",
      "Smart room & bed allocation",
      "Police verification automation",
      "Digital agreement generation",
    ],
    benefits: [
      "Reduce onboarding time from days to 30 minutes",
      "100% digital paperless process",
      "Enhanced security with verified tenants",
      "Eliminate manual data entry errors",
      "Compliance-ready documentation",
    ],
    workflow: [
      "Tenant submits digital application",
      "Document upload & AI verification",
      "Background check automation",
      "Smart room allocation",
      "Digital agreement signing",
     
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1551836026-d5c2c5af78e4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
      "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
    ],
    stats: [
      { label: "Time Saved", value: "90%" },
      { label: "Error Reduction", value: "99%" },
      { label: "Compliance", value: "100%" },
    ],
  },
  {
    id: "payments-billing",
    title: "Automated Payments & Billing",
    tag: "Finance",
    description: "Secure rent collection with automated invoices and reminders.",
    longDescription: "Streamline your financial operations with our comprehensive payment and billing system. Automate rent collection through UPI, credit/debit cards, net banking, and wallets. The system generates invoices automatically, sends payment reminders, applies late fees based on configurable rules, and provides downloadable receipts. Advanced features include partial payments, advance payments, security deposit management, and detailed financial reporting for complete transparency.",
    icon: FaMoneyBillWave,
    color: "from-violet-500 to-purple-600",
    points: [
      "UPI, cards, net banking & wallets",
      "Automated late fee calculation",
      "Downloadable receipts & invoices",
      "Partial & advance payment support",
      "Security deposit management",
    ],
    benefits: [
      "Zero manual accounting work",
      "Improve collection rate by 60%",
      "Real-time financial tracking",
      "Automated GST compliance",
      "Digital audit trail",
    ],
    workflow: [
      "System auto-generates monthly invoices",
      "Automated payment reminders via SMS/email",
      "Tenant pays through preferred method",
      "Instant receipt generation",
      "Late fee auto-application",
      "Real-time dashboard updates",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1554224155-6726b3ff858f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
      "https://images.unsplash.com/photo-1605902711622-cfb43c44367f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
    ],
    stats: [
      { label: "Collection Speed", value: "60% faster" },
      { label: "Late Payments", value: "Reduced by 80%" },
      { label: "Manual Work", value: "Eliminated 100%" },
    ],
  },
  {
    id: "room-allocation",
    title: "Intelligent Room Allocation",
    tag: "Rooms",
    description: "Smart allocation based on availability, gender, and preferences.",
    longDescription: "Never worry about room allocation again with our AI-powered allocation system. The platform automatically assigns rooms based on multiple parameters: gender compatibility, tenant preferences, special requirements, duration of stay, and payment status. Real-time vacancy tracking prevents overbooking while optimization algorithms maximize space utilization. Features include roommate matching, floor-wise distribution, and special accommodation handling for differently-abled residents.",
    icon: FaBed,
    color: "from-pink-500 to-rose-600",
    points: [
      "Gender & preference-based allocation",
      "Real-time vacancy visualization",
      "No overbooking guarantee",
      "Roommate compatibility matching",
      "Special needs accommodation",
    ],
    benefits: [
      "100% accurate room assignments",
      "Eliminate allocation conflicts",
      "Maximize space utilization",
      "Happy tenants with preferred rooms",
      "Automated waitlist management",
    ],
    workflow: [
      "System analyzes tenant preferences",
      "Checks real-time room availability",
      "AI suggests optimal room assignment",
      "Admin approves or modifies",
      "Automatic notification to tenant",
      "Digital room key assignment",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
    ],
    stats: [
      { label: "Allocation Speed", value: "5x faster" },
      { label: "Tenant Satisfaction", value: "+45%" },
      { label: "Space Utilization", value: "Optimized 95%" },
    ],
  },
  {
    id: "maintenance",
    title: "Maintenance & Complaint Management",
    tag: "Support",
    description: "Track issues with photos, priorities, and SLA tracking.",
    longDescription: "Transform your maintenance operations with our comprehensive ticketing system. Residents can raise complaints with photos/videos, categorize by priority (emergency, high, medium, low), and track resolution in real-time. The system automatically assigns tickets to appropriate staff, sets SLAs based on priority, and sends updates to residents. Features include preventive maintenance scheduling, inventory tracking for spare parts, vendor management, and detailed analytics on response times and resolution rates.",
    icon: FaTools,
    color: "from-amber-500 to-orange-600",
    points: [
      "Photo/video-based complaint logging",
      "Priority-based staff assignment",
      "Real-time resolution tracking",
      "Preventive maintenance scheduling",
      "Vendor & inventory management",
    ],
    benefits: [
      "Reduce resolution time by 70%",
      "Improve resident satisfaction",
      "Track staff performance metrics",
      "Prevent recurring issues",
      "Centralized maintenance history",
    ],
    workflow: [
      "Resident raises ticket with photos",
      "System categorizes priority",
      "Auto-assigns to appropriate staff",
      "Staff updates status & resolution",
      "Resident confirms satisfaction",
      "System logs for analytics",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
    ],
    stats: [
      { label: "Resolution Time", value: "70% faster" },
      { label: "First Contact Resolution", value: "85%" },
      { label: "Resident Satisfaction", value: "+50%" },
    ],
  },
  {
    id: "food-management",
    title: "Mess & Food Management",
    tag: "Food",
    description: "Manage daily menus, meal counts, and food planning efficiently.",
    longDescription: "Revolutionize your hostel mess management with our comprehensive food management system. Create weekly/monthly menus with nutritional information, track daily meal counts to prevent wastage, manage inventory automatically, and handle special dietary requirements. The system calculates exact ingredient requirements, generates shopping lists, tracks food costs, and manages mess staff schedules. Features include feedback collection, meal preference tracking, and integration with billing for mess charges.",
    icon: FaUtensils,
    color: "from-lime-500 to-green-600",
    points: [
      "Weekly/monthly menu planning",
      "Real-time meal count tracking",
      "Inventory & ingredient management",
      "Special diet management",
      "Food cost analytics",
    ],
    benefits: [
      "Reduce food wastage by 60%",
      "Accurate cost tracking",
      "Happy residents with preferred meals",
      "Automated inventory ordering",
      "Nutritional balance monitoring",
    ],
    workflow: [
      "Plan menu for coming week",
      "Residents mark meal preferences",
      "System calculates ingredient needs",
      "Automatic inventory updates",
      "Meal count tracking & feedback",
      "Cost analysis & reporting",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
    ],
    stats: [
      { label: "Food Wastage", value: "Reduced 60%" },
      { label: "Cost Savings", value: "25%" },
      { label: "Resident Satisfaction", value: "+40%" },
    ],
  },
  {
    id: "announcements",
    title: "Announcements & Broadcasts",
    tag: "Communication",
    description: "Send instant updates to all residents via multiple channels.",
    longDescription: "Keep everyone informed with our multi-channel announcement system. Send instant notifications via push notifications, SMS, email, and in-app messages. Schedule announcements for future dates, target specific groups (floor-wise, wing-wise, or all), and track delivery and read receipts. Perfect for event announcements, maintenance notices, payment reminders, emergency alerts, and general updates. The system ensures 100% reach with fail-safe delivery mechanisms.",
    icon: FaBullhorn,
    color: "from-sky-500 to-cyan-600",
    points: [
      "Push, SMS, email & in-app notifications",
      "Scheduled & recurring announcements",
      "Targeted group messaging",
      "Delivery & read tracking",
      "Emergency alert system",
    ],
    benefits: [
      "100% communication reach",
      "Reduce missed announcements",
      "Targeted messaging saves time",
      "Track engagement metrics",
      "Emergency broadcast capability",
    ],
    workflow: [
      "Compose announcement with media",
      "Select target audience",
      "Choose delivery channels",
      "Schedule or send immediately",
      "Track delivery & engagement",
      "Generate reports on reach",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1559136555-9303baea8ebd?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
      "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
    ],
    stats: [
      { label: "Announcement Reach", value: "100%" },
      { label: "Response Rate", value: "+75%" },
      { label: "Time Saved", value: "80%" },
    ],
  },
  {
    id: "analytics",
    title: "Advanced Analytics & Reports",
    tag: "Insights",
    description: "Real-time dashboards for occupancy, revenue, and performance.",
    longDescription: "Make data-driven decisions with our powerful analytics platform. Get real-time insights into occupancy rates, revenue trends, tenant demographics, staff performance, and operational efficiency. Customizable dashboards show exactly what you need, while automated reports can be scheduled for daily/weekly/monthly delivery. Features include predictive analytics for occupancy forecasting, comparative analysis with industry benchmarks, and detailed financial reporting with GST compliance.",
    icon: FaChartLine,
    color: "from-fuchsia-500 to-purple-600",
    points: [
      "Real-time occupancy dashboards",
      "Revenue tracking & forecasting",
      "Custom report generation",
      "Predictive analytics",
      "Staff performance metrics",
    ],
    benefits: [
      "Make informed business decisions",
      "Identify revenue opportunities",
      "Monitor operational efficiency",
      "Benchmark against industry standards",
      "Automated compliance reporting",
    ],
    workflow: [
      "Data collection from all modules",
      "Real-time processing & analysis",
      "Dashboard visualization",
      "Custom report generation",
      "Scheduled report delivery",
      "Predictive insights generation",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
    ],
    stats: [
      { label: "Decision Speed", value: "3x faster" },
      { label: "Revenue Insights", value: "Real-time" },
      { label: "Report Generation", value: "Automated 100%" },
    ],
  },
  {
    id: "mobile-app",
    title: "Mobile Apps (Admin & Tenant)",
    tag: "Mobile",
    description: "Manage everything on the go with powerful mobile apps.",
    longDescription: "Take your hostel management mobile with our feature-rich Android and iOS apps. Admins get complete control from their phones: approve bookings, track payments, handle complaints, and monitor operations. Tenants enjoy seamless experience: book rooms, pay rent, raise complaints, check announcements, and access digital agreements. Both apps work offline with sync capabilities, support multiple languages, and offer biometric login for enhanced security.",
    icon: FaMobileAlt,
    color: "from-indigo-500 to-blue-600",
    points: [
      "Tenant booking & payment app",
      "Admin control panel app",
      "Offline functionality",
      "Multi-language support",
      "Biometric authentication",
    ],
    benefits: [
      "Manage anywhere, anytime",
      "Tenant convenience improves satisfaction",
      "Real-time updates on mobile",
      "Reduce dependency on computers",
      "Enhanced security with mobile auth",
    ],
    workflow: [
      "Download app from store",
      "Secure login with biometrics",
      "Access all features on mobile",
      "Real-time sync with cloud",
      "Push notifications for updates",
      "Offline capability with auto-sync",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
    ],
    stats: [
      { label: "Admin Mobility", value: "100%" },
      { label: "Tenant Engagement", value: "+65%" },
      { label: "Response Time", value: "Reduced 70%" },
    ],
  },
  {
    id: "support",
    title: "24/7 Dedicated Support",
    tag: "Support",
    description: "Round-the-clock assistance with priority escalation.",
    longDescription: "Get peace of mind with our comprehensive 24/7 support system. Multiple channels including live chat, phone, email, and video call support ensure you're never stuck. Priority escalation for critical issues, dedicated account managers for large hostels, and comprehensive knowledge base with tutorials. Our support team specializes in hostel management and can help with setup, training, troubleshooting, and optimization. Regular health checks and proactive monitoring prevent issues before they occur.",
    icon: FaHeadset,
    color: "from-red-500 to-rose-600",
    points: [
      "24/7 live chat & phone support",
      "Priority escalation matrix",
      "Dedicated account managers",
      "Comprehensive knowledge base",
      "Proactive system monitoring",
    ],
    benefits: [
      "Zero downtime assurance",
      "Expert guidance always available",
      "Quick resolution of critical issues",
      "Continuous system optimization",
      "Peace of mind for hostel owners",
    ],
    workflow: [
      "Raise query via preferred channel",
      "Automatic ticket generation",
      "Expert assignment based on issue",
      "Real-time resolution tracking",
      "Satisfaction confirmation",
      "Preventive measures implementation",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000",
    ],
    stats: [
      { label: "Response Time", value: "< 2 minutes" },
      { label: "Resolution Rate", value: "98%" },
      { label: "Customer Satisfaction", value: "99%" },
    ],
  },
];
