export const roomsData = [
  {
    id: "rr-residency",
    name: "RR Residency",
    city: "Hyderabad",
    area: "Madhapur",
    description:
      "RR Residency offers comfortable and affordable stays with modern amenities. Ideal for business travelers and couples.",
    roomType: "Deluxe Room",
    maxGuests: 2,
    pricePerNight: 1799,
    rating: 4.4,
    reviews: 212,
    verified: true,
    freeCancellation: true,
    checkIn: "12:00 PM",
    checkOut: "11:00 AM",
    amenities: [
      "Free WiFi",
      "Air Conditioning",
      "TV",
      "Hot Water",
      "Power Backup",
      "Daily Housekeeping",
      "Parking",
    ],
    houseRules: [
      "Couples are welcome",
      "Valid ID proof required",
      "No smoking inside rooms",
      "Pets not allowed",
    ],
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7",
      "https://images.unsplash.com/photo-1555854877-bab0e564b8d5",
    ],
  },

  {
    id: "comfort-inn",
    name: "Comfort Inn",
    city: "Hyderabad",
    area: "Gachibowli",
    description:
      "Comfort Inn provides premium rooms with excellent connectivity to IT hubs and business districts.",
    roomType: "Executive Room",
    maxGuests: 3,
    pricePerNight: 2299,
    rating: 4.6,
    reviews: 180,
    verified: true,
    freeCancellation: false,
    checkIn: "1:00 PM",
    checkOut: "11:00 AM",
    amenities: [
      "Free WiFi",
      "AC",
      "TV",
      "Lift",
      "Room Service",
      "24x7 Security",
    ],
    houseRules: [
      "Unmarried couples allowed",
      "Local IDs allowed",
      "No loud music after 10 PM",
    ],
    images: [
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304",
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00",
    ],
  },
];
